version: "3.7"
services:
  flairpostremoverbot:
    build: .
    environment:
      TZ: "America/New_York"
    volumes:
      - "./config:/usr/src/app/config:ro"
      - "./data:/usr/src/app/data"
    restart: always
    image: flairpostremoverbot
